_core:
  default_config_hash: DxsZkkrod97cQtkSKNioAnuZewcgL_MHfh1HYLTuAS4
minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 8
minimum_width: 200
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
disabled_themes:
  seven: '0'
  mungo: '0'
chosen_include: 2
placeholder_text_multiple: 'Choose some option'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
include: 2
