minified: 1
headline_text: 'Vi bruger cookies og lokal lagring bl.a. for at huske dine indstillinger og gøre din oplevelse bedre. Ved at bruge sitet accepterer du dette.'
accept_button_text: OK
read_more_button_text: 'Læs mere'
theme: dark-bottom
path: /
domain: ''
expiry: '365'
target: _blank
_core:
  default_config_hash: _tr-X8c0EtWB8CElgT53wtsgTQfB_Th-MMGaw7xA6bo
theme_path: ''
customise: 1
cookie_policy: '2010'
container: ''
