extlink_exclude_admin_routes: false
extlink_target: true
extlink_subdomains: false
extlink_alert: false
extlink_alert_text: ''
extlink_exclude: '^(http:\/\/|https:\/\/)((www|nyt)\.)?dds\.dk(\/)?'
extlink_include: ''
extlink_class: '0'
extlink_label: '(link is external)'
extlink_img_class: false
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_mailto_class: '0'
extlink_mailto_label: '(link sends email)'
