features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 0
logo:
  use_default: 1
favicon:
  use_default: 1
badge_cover_image_path: 'public://maerkeunivers-cover.jpg'
badge_cover_image: ''
