features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
badge_cover_image_path: ''
badge_cover_image: ''
badge_page_title: Mærkeunivers
badge_page_description: 'Her er en beskrivelse af mærke-universet.'
