# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: 'drupal'

# The runtime the application uses.
type: "php:7.0"

# Configuration of the build of this application.
build:
    flavor: composer

# The build-time dependencies of the app.
dependencies:
    php:
        "drush/drush": "^8.0"
        "drupal/console": "@stable"
    nodejs:
        "gulp-cli": "latest"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"
    solr: "solr:ddssolr"
    # redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        "/":
            # The folder to serve static assets for this location from.
            # (Relative to the application root.)
            root: "web"

            # How long to allow static assets from this location to be cached.
            # (Can be a time or -1 for no caching. Times can be suffixed with
            # "ms" (milliseconds), "s" (seconds), "m" (minutes), "h" (hours),
            # "d" (days), "w" (weeks), "M" (months, 30d) or "y" (years, 365d).)
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # (Can be true, false or a URI path string.)
            passthru: "/index.php"
            
            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 7d
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

# The size of the persistent disk of the application (in MB).
disk: 11264

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # Build theme assets.
    build: |
      npm install
      gulp build
      curl -sS https://platform.sh/cli/installer | php
      # Setup filebeat
      mkdir /app/bin
      curl -L  -o /app/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      chmod +x /app/bin/jq
      mkdir /app/services/logstream/service/filebeat/dist
      curl -L -o /tmp/filebeat.tar.gz https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.6.1-linux-x86_64.tar.gz
      mkdir -p /tmp/filebeat/dist
      tar xzvf /tmp/filebeat.tar.gz --strip-components=1 -C /app/services/logstream/service/filebeat/dist
      chmod +x /app/services/logstream/service/run

    # We run deploy hook after your application has been deployed and started.
    deploy: |
      cd web
      drush -y cache-rebuild
      drush -y updatedb --entity-updates
      drush -y config-import
      mkdir -p /tmp/filebeat/config
      rm -f /tmp/filebeat/.is_configured
      # Get the ingest token from config if it exists and prepare a filebeat config.
      HUMIO_INGEST_TOKEN=$( echo "$PLATFORM_VARIABLES" | base64 --decode | /app/bin/jq -r "(.HUMIO_INGEST_TOKEN)")
      if [ ! -z "${HUMIO_INGEST_TOKEN}" ]; then
        cat /app/services/logstream/service/filebeat/config/filebeat-template.yml | envsubst > /tmp/filebeat/config/filebeat.yml
        # Signal that filebeat should be available.
        touch /tmp/filebeat/.is_configured
      fi

# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/2 * * * *"
        cmd: "cd web ; drush core-cron"
    logs:
        # Export logs as often as possible. Platform.sh currently translates
        # this to every 5 minutes.
        spec: "* * * * *"
        # If filebeat is configured, check if its already running, and if not
        # launch a new instance that will do a a pass and exit.
        cmd: "test -f /tmp/filebeat/.is_configured && ( (ps aux |grep -E 'dist/filebeat\\s' > /dev/null) || /app/services/logstream/service/run )"
    snapshot:
        spec: '15 0 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = "master" ] || [ "$PLATFORM_BRANCH" = "develop" ]; then
                platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 3 am (UTC) on the 1st and 15th of every month.
        spec: '0 3 1,15 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi
