checks:
  php:
    code_rating: true
    excluded_dependencies:
      - drupal/core

build:
  environment:
    php: '7.0.8'
    node: 'v6.2.0'
    # Disable default dependencies - we where getting postgresql and redis.
    postgresql: false
    redis: false
  dependencies:
    after:
      - 'mkdir tests/reports'
  tests:
    override:
      -
        command: 'composer phpcs-checkstyle'
        analysis:
          file: 'tests/reports/phpcs-checkstyle.xml'
          format: 'php-cs-checkstyle'

build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'

filter:
    paths:
      - 'web/modules/custom/*'
      - 'web/profiles/custom/*'
      - 'web/themes/custom/*'
