packages:
    ajgl/breakpoint-twig-extension: 0.3.0
    alchemy/zippy: 0.4.3
    asm89/stack-cors: 1.2.0
    behat/mink: v1.7.1
    behat/mink-browserkit-driver: v1.3.2
    behat/mink-goutte-driver: v1.2.1
    commerceguys/addressing: v1.0.0-beta3
    commerceguys/enum: v1.0
    commerceguys/intl: v0.7.4
    composer/installers: v1.3.0
    composer/semver: 1.4.2
    consolidation/annotated-command: 2.8.1
    consolidation/output-formatters: 3.1.12
    cweagans/composer-patches: 1.6.5
    dflydev/dot-access-configuration: v1.0.2
    dflydev/dot-access-data: v1.1.0
    dflydev/placeholder-resolver: v1.0.2
    dnoegel/php-xdg-base-dir: '0.1'
    doctrine/annotations: v1.4.0
    doctrine/cache: v1.6.2
    doctrine/collections: v1.4.0
    doctrine/common: v2.7.3
    doctrine/inflector: v1.2.0
    doctrine/instantiator: 1.0.5
    doctrine/lexer: v1.0.1
    drmonty/chosen: 1.6.1
    drupal-composer/drupal-scaffold: 2.3.0
    drupal/address: 1.4.0
    drupal/admin_toolbar: 1.25.0
    drupal/better_exposed_filters: 3.0.0-alpha5
    drupal/chosen: 2.6.0
    drupal/chosen_lib: 2.6.0
    drupal/coder: 8.3.1
    drupal/console: 1.8.0
    drupal/console-core: 1.8.0
    drupal/console-dotenv: 0.3.0
    drupal/console-en: 1.8.0
    drupal/console-extend-plugin: 0.9.2
    drupal/cookieconsent: 1.4.0
    drupal/core: 8.6.7
    drupal/crop: 1.5.0
    drupal/ctools: 3.0.0
    drupal/dropguard: 1.2.0
    drupal/editor_advanced_link: 1.4.0
    drupal/entity: 1.0.0-rc1
    drupal/entity_reference_revisions: 1.6.0
    drupal/extlink: 1.1.0
    drupal/facets: 1.2.0
    drupal/field_group: 1.0.0-rc6
    drupal/field_redirection: dev-2.x
    drupal/forward: 2.0.0
    drupal/google_analytics: 2.2.0
    drupal/http2_server_push: 1.0.0
    drupal/image_widget_crop: 2.0.0
    drupal/inline_entity_form: 1.0.0-beta1
    drupal/link_attributes: 1.1.0
    drupal/maxlength: 1.0.0-beta1
    drupal/media_entity: 1.6.0
    drupal/media_entity_image: 1.2.0
    drupal/metatag: 1.3.0
    drupal/monitoring: 1.4.0
    drupal/paragraphs: 1.2.0
    drupal/pathauto: 1.0.0
    drupal/redirect: 1.0.0-beta1
    drupal/reloadtina: 1.0.0-alpha1
    drupal/search_api: 1.6.0
    drupal/search_api_exclude_entity: 1.0.0-beta2
    drupal/search_api_solr: 1.2.0
    drupal/stage_file_proxy: 1.0.0-alpha3
    drupal/system_status: 2.5.0
    drupal/taxonomy_access_fix: 2.1.0
    drupal/token: 1.0.0
    drupal/twig_xdebug: 1.0.0
    drupal/video_embed_field: 1.5.0
    drush/drush: 8.1.15
    easyrdf/easyrdf: 0.9.1
    egulias/email-validator: 1.2.15
    fabpot/goutte: v3.2.1
    gabordemooij/redbean: v4.3.4
    guzzlehttp/guzzle: 6.3.3
    guzzlehttp/promises: v1.3.1
    guzzlehttp/psr7: 1.5.2
    jakub-onderka/php-console-color: '0.1'
    jakub-onderka/php-console-highlighter: v0.3.2
    jcalderonzumba/gastonjs: v1.0.3
    jcalderonzumba/mink-phantomjs-driver: v0.3.3
    joachim-n/composer-manifest: 1.0.1
    masterminds/html5: 2.5.0
    mikey179/vfsstream: v1.6.5
    nikic/php-parser: v3.1.1
    paragonie/random_compat: v2.0.18
    pear/console_table: v1.3.0
    phpdocumentor/reflection-docblock: 2.0.5
    phpspec/prophecy: v1.7.0
    phpunit/php-code-coverage: 2.2.4
    phpunit/php-file-iterator: 1.4.2
    phpunit/php-text-template: 1.2.1
    phpunit/php-timer: 1.0.9
    phpunit/php-token-stream: 1.4.11
    phpunit/phpunit: 4.8.36
    phpunit/phpunit-mock-objects: 2.3.8
    psr/cache: 1.0.1
    psr/container: 1.0.0
    psr/http-message: 1.0.1
    psr/log: 1.1.0
    psr/simple-cache: 1.0.1
    psy/psysh: v0.8.13
    ralouphie/getallheaders: 2.0.5
    sebastian/comparator: 1.2.4
    sebastian/diff: 1.4.3
    sebastian/environment: 1.3.8
    sebastian/exporter: 1.2.2
    sebastian/global-state: 1.1.1
    sebastian/recursion-context: 1.0.5
    sebastian/version: 1.0.6
    solarium/solarium: 3.8.1
    squizlabs/php_codesniffer: 3.4.0
    stack/builder: v1.0.5
    stecman/symfony-console-completion: 0.7.0
    symfony-cmf/routing: 1.4.1
    symfony/browser-kit: v3.4.21
    symfony/cache: v3.4.21
    symfony/class-loader: v3.4.21
    symfony/config: v3.4.21
    symfony/console: v3.4.21
    symfony/css-selector: v2.8.49
    symfony/debug: v3.4.21
    symfony/dependency-injection: v3.4.21
    symfony/dom-crawler: v3.4.21
    symfony/event-dispatcher: v3.4.21
    symfony/expression-language: v3.4.21
    symfony/filesystem: v3.4.21
    symfony/finder: v3.4.21
    symfony/http-foundation: v3.4.21
    symfony/http-kernel: v3.4.21
    symfony/polyfill-apcu: v1.10.0
    symfony/polyfill-ctype: v1.10.0
    symfony/polyfill-iconv: v1.10.0
    symfony/polyfill-mbstring: v1.10.0
    symfony/polyfill-php70: v1.10.0
    symfony/process: v3.4.21
    symfony/psr-http-message-bridge: v1.1.0
    symfony/routing: v3.4.21
    symfony/serializer: v3.4.21
    symfony/translation: v3.4.21
    symfony/validator: v3.4.21
    symfony/var-dumper: v3.4.21
    symfony/yaml: v3.4.21
    twig/twig: v1.37.1
    typo3/phar-stream-wrapper: v2.0.1
    vlucas/phpdotenv: v2.4.0
    webflo/drupal-finder: 1.1.0
    webmozart/assert: 1.2.0
    webmozart/path-util: 2.3.0
    woothemes/flexslider: 2.6.3
    zendframework/zend-diactoros: 1.8.6
    zendframework/zend-escaper: 2.6.0
    zendframework/zend-feed: 2.10.3
    zendframework/zend-stdlib: 3.2.1
