version: "2"

services:
  # https proxy, hands connection down to the web-server.
  https:
    image: zazukoians/hitch
    ports:
      - '443'
    environment:
      HITCH_PARAMS: --backend=[web]:80 --frontend=[*]:443
    links:
      - web

  # Pure web-server, hands php-requests off to fpm.
  web:
    image: reload/drupal-apache-fpm
    ports:
      - '80'
    volumes:
      # Temporary mount for the cron-configuration, we'll copy it into place
      # with correct ownership via the init-script.
      - './docker/cron/drupal-cron:/root/tmp.drupal-cron:ro'
      - './docker/cron/setup-cron.sh:/etc/my_init.d/setup-cron.sh'
    volumes_from:
      - webroot
    links:
      - fpm

  # Instance of the php-image configured to serve fpm-requests.
  fpm:
    image: reload/drupal-php7-fpm
    ports:
      - '9000'
    volumes_from:
      - webroot
    links:
      - db
      - solr
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"

  # Mariadb database, initialized with a nighly pre-build datadir.
  db:
    image: reload/db-datadir:ddsdk2016-master-latest-fulldb
    ports:
      - '3306'
    # Switch to the "mariadb" image and uncomment the following if you want to
    # import a custom databasedump
    #  volumes:
    #    - './docker/my-custom-db-dump.sql:/docker-entrypoint-initdb.d/100-db.sql'

    # Notice the following environment-variables only takes effect if we're 
    # using a raw mariadb image. We're just leaving the values used during
    # the datadir build here for reference.
    # see https://github.com/reload/docker-db-datadir-worker/blob/master/opt/datadir-preinit/docker-compose.template.yml
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  # Drush startet off of the common php-image.
  drush:
    image: reload/drupal-php7-fpm
    entrypoint: /usr/local/bin/drush
    command: version
    volumes_from:
      - webroot
    working_dir: /var/www/web
    links:
      - db
      - solr
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

  solr:
    image: blinkreaction/drupal-solr:4.x-stable
    ports:
      - '8983'
    volumes:
      - './web/modules/contrib/search_api_solr/solr-conf/4.x:/var/lib/solr/conf:ro'

  # Webroot and volumned paths needs to be accessible from multiple containers so
  # we set up all paths once and for all via a single volumne-container.
  webroot:
    image: tianon/true
    volumes:
      - './web:/var/www/web:rw'
      - './scripts:/var/www/scripts'
      - './vendor:/var/www/vendor:ro'
      - './configuration:/var/www/configuration:rw'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
