forward_interface_title: 'Send denne [forward:entity-type]'
forward_link_title: 'Videresend denne [forward:entity-type] til en ven.'
forward_form_instructions: 'Del <em>[forward:entity-title]</em> fra [site:name].'
forward_form_confirmation: 'Indholdet er nu sent.'
forward_email_subject: '[forward:sender-name] har sendt en [dds_article:type] til dig fra [site:name]'
forward_email_message: '[forward:sender-name] har delt en [dds_article:type] fra [site:name] med dig.'
forward_flood_control_error: 'Du kan ikke sende mere end @number messages stykker indhold i timen. Prøv igen senere.'
forward_max_recipients_error: 'Du kan kun sende indholdet til én enkelt modtager.'
