root: true
env:
  es6: true
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "eslint-config-prettier"
rules:
  "import/order": "error"
globals:
  "Drupal": writable
  "jQuery": writable
  "drupalSettings": writable
  "drupalTranslations": writable

