<?php

/**
 * @file
 * Functionality for articles.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Mail\MailFormatHelper;
use Drupal\dds_article\DdsArticleInterface;

/**
 * Implements hook_form_alter().
 */
function dds_article_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Bail if the form is not related edit or creating an article.
  if (!in_array($form_id, ['node_article_edit_form', 'node_article_form'])) {
    return;
  }

  // Add custom validate for 'field_content_author'.
  if (!empty($form['field_content_author'])) {
    $form['#validate'][] = 'dds_article_node_article_edit_form_validate';
  }
}

/**
 * Custom validate for 'node_article form' and 'node_article_edit_form'.
 */
function dds_article_node_article_edit_form_validate(&$form, FormStateInterface $form_state) {

  // Get user input.
  $field_article_type = $form_state->getValue('field_article_type');
  $field_content_author = $form_state->getValue('field_content_author');

  // Set error if author is not sat and the article type is simple.
  if (!isset($field_article_type[0]['value']) || ($field_article_type[0]['value'] !== DdsArticleInterface::DDS_ARTICLE_ARTICLE_TYPE_SIMPLE && empty($field_content_author))) {
    $form_state->setError($form['field_content_author'], t('Content author is required!'));
  }
}

/**
 * Implements hook_forward_token().
 */
function dds_article_forward_token(FormStateInterface $form_state) {
  return [
    'dds_article' => [
      'type' => 'dds_article:type',
    ],
  ];
}

/**
 * Implements hook_forward_mail_pre_render_alter().
 */
function dds_article_forward_mail_pre_render_alter(array &$render_array, FormStateInterface &$form_state) {
  if (empty($render_array['#message']) ||
    empty($render_array['#message']['#plain_text'])) {
    return;
  }

  // Convert message to real plain text (i.e. newlines are converted tp `<br>`
  // and we need to get rid of those).
  $render_array['#message']['#plain_text'] = MailFormatHelper::htmlToText($render_array['#message']['#plain_text']);
}
