<?php

/**
 * @file
 * Hooks and functionality targeted at the administrative interface.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Language\LanguageInterface;

/**
 * Implements hook_pathauto_alias_alter().
 */
function dds_admin_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved as language neutral.
  // All our content is currently in Danish but editors and admins may browse
  // the site in Danish or English. Aliases will be generated either for the
  // language of the content or a specific language. We want all users to be
  // able to use paths and do not want to deal with per language aliases.
  $context['language'] = LanguageInterface::LANGCODE_NOT_SPECIFIED;
}

/**
 * Implements hook_admin_editor_js_settings_alter().
 *
 * Switches a deprecated ckeditor configuration from false to true.
 */
function dds_admin_editor_js_settings_alter(array &$settings) {
  if (!empty($settings['editor']['formats']) && is_array($settings['editor']['formats'])) {
    foreach ($settings['editor']['formats'] as &$format_settings) {
      if ($format_settings['editor'] === 'ckeditor') {
        // CKeditor 4.6 deprecated pasteFromWordRemoveFontStyles and switched
        // its default from true to false. As a fix until core comes up with a
        // better way to solve this (see https://www.drupal.org/node/2871539 ).
        $format_settings['editorSettings']['pasteFromWordRemoveFontStyles'] = TRUE;

        // Tweak autogrow settings, meaning how high the input box is, based
        // on how much content is inside.
        $format_settings['editorSettings']['autoGrow_onStartup'] = FALSE;
        $format_settings['editorSettings']['autoGrow_minHeight'] = 250;
        $format_settings['editorSettings']['autoGrow_maxHeight'] = 400;
      }
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * Unregister file usage for deleted entities.
 *
 * This should be cores responsibility, but there are some issues:
 *
 * @see https://www.drupal.org/project/drupal/issues/1239558
 * @see https://www.drupal.org/project/drupal/issues/2885434
 */
function dds_admin_entity_delete(EntityInterface $entity) {
  $entity_type = $entity->getEntityTypeId();
  $entity_id = $entity->id();

  // Lookup the files which the entity has registered it uses.
  $fids = \Drupal::database()
    ->select('file_usage', 'fu')
    ->fields('fu', ['fid'])
    ->condition('module', 'file')
    ->condition('type', $entity_type)
    ->condition('id', $entity_id)
    ->execute()
    ->fetchCol();

  // Bail out if no files are used.
  if (empty($fids)) {
    return;
  }

  /** @var \Drupal\file\FileUsage\FileUsageInterface $file_usage */
  $file_usage = \Drupal::service('file.usage');

  // Remove the entity's usage of the files (the magic 0 means remove all
  // usages).
  foreach ($fids as $fid) {
    $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
    $file_usage->delete($file, 'file', $entity_type, $entity_id, 0);
  }

  // Invalidate the file_list cache to get the updated usage reflected
  // immediately in `admin/content/files`.
  \Drupal::service('cache_tags.invalidator')->invalidateTags(['file_list']);
}
