<?php

/**
 * @file
 * Functionality for activities.
 */

use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\File\FileSystemInterface;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;

/**
 * @file
 * Functionality related to activities and integration to aktdb.
 */

/**
 * Implements hook_node_presave().
 *
 * Populates the node with data fetched from the activity-database.
 */
//function dds_activity_node_presave(Node $node) {
//  $logger = \Drupal::logger('dds_activity');
//
//  // Ensure we have all the data we need.
//  if (!$node->hasField('field_activity_id') || !is_numeric($node->get('field_activity_id')->value)) {
//    return;
//  }
//  $activity_id = (int) $node->get('field_activity_id')->value;
//
//  // Get the fetcher and populate the simple text-fields.
//  /** @var \Drupal\dds_activity\ActivityFetcher $activity_fetcher */
//  $activity_fetcher = \Drupal::service('dds_activity.activity_fetcher');
//  if (!$activity_fetcher->loadActivity($activity_id)) {
//    $logger->error('Could not load activity with id @id', ['@id' => $activity_id]);
//    return;
//  }
//  $node->set('title', $activity_fetcher->getTitle());
//  $node->set('field_subtitle', $activity_fetcher->getDescription());
//
//  // Then fetch the image and attach it to the node.
//  // First off, prepare the directory where we're going to put the image.
//  $file_destination_dir = 'public://aktivws/' . $activity_id;
//  if (!\Drupal::service('file_system')->prepareDirectory($file_destination_dir, FileSystemInterface::CREATE_DIRECTORY)) {
//    $logger->error('Could not prepare destination directory @dir', ['@dir' => $file_destination_dir]);
//    return;
//  }
//
//  // The prepare the destination path and download the file.
//  $file_destination = $file_destination_dir . '/' . $activity_fetcher->getImageFilename();
//
//  /** @var \Drupal\file\FileInterface $file */
//  $image_source_url = $activity_fetcher->getImageUrl();
//  $file = system_retrieve_file($image_source_url, $file_destination, TRUE, FILE_EXISTS_REPLACE);
//  if ($file === FALSE) {
//    $logger->error(
//      'Could download activity image from @url to @destination',
//      [
//        '@url' => $image_source_url,
//        '@destination' => $file_destination,
//      ]
//    );
//    return;
//  }
//  // TODO: we don't do anything to handle file_usage - out of the box we
//  // currently register two usages - probably core and media.
//  $image_media = Media::create([
//    'bundle' => 'image',
//    'uid' => '1',
//    'status' => TRUE,
//    'field_image' => [
//      'target_id' => $file->id(),
//      'alt' => $activity_fetcher->getTitle(),
//    ],
//  ]);
//
//  try {
//    $image_media->save();
//  }
//  catch (EntityStorageException $e) {
//    watchdog_exception('dds_activity', $e);
//    return;
//  }
//
//  // If the activity already have an image, overwrite the reference and then
//  // delete the media.
//  if (!empty($node->field_main_media->target_id)) {
//    // Get the current id.
//    $media_to_be_deleted = $node->field_main_media->target_id;
//    // Overwrite the current reference.
//    $node->field_main_media->target_id = $image_media->id();
//    // Then delete the old media if we can load it.
//    $old_media = Media::load($media_to_be_deleted);
//    if (!empty($old_media)) {
//      $old_media->delete();
//    }
//  }
//  else {
//    // The activity does not have an image - add it.
//    $node->field_main_media->appendItem(['target_id' => $image_media->id()]);
//  }
//}
