<?php

/**
 * @file
 * Theming of a image with text.
 */

/**
 * Implements hook_theme().
 */
function dds_top_image_theme() {
  $hooks = array();

  $hooks['dds_top_image'] = [
    'variables' => array(
      'title' => NULL,
      'subtitle' => NULL,
      'image' => NULL,
      'image_uri' => NULL,
    ),
  ];

  return $hooks;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_dds_top_image(&$variables) {
  // If we have a image-uri, generate a render-array for it.
  if (!empty($variables['image_uri'])) {
    $variables['image'] = _mungo_render_image_uri_with_responsive_style($variables['image_uri'], '16_9_responsive');
  }

}
