on: pull_request
name: JavaScript
jobs:

  # See https://github.com/reload/action-jsts-quality
  eslint-reviewdog:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./web/themes/custom/mungo

      - name: JSTS Quality
        uses: reload/action-jsts-quality@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: './web/themes/custom/mungo'
          prettier_target: './assets_src/js/**/*'
          eslint_target: './assets_src/js'
