on: pull_request
name: Validate

# Detect if this action is already running, and cancel it.
# This most likely happened because a second push has been made to a branch.
concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    name: Lint PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer
          coverage: none

      - name: Composer validate and update
        run: |
          composer validate --no-check-all --no-check-publish
          composer update --lock --quiet
            # Add vendor/bin to PATH for subsequent steps, see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
            composer config bin-dir --absolute >> "${GITHUB_PATH}"

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress

      - name: Run phpcs
        uses: reload/action-phpcs@main
        with:
          reviewdog_token: ${{ secrets.GITHUB_TOKEN }}

      - name: PHPStan analyse
        run: |
          phpstan
