on: pull_request
name: SCSS
jobs:

  # See https://github.com/reload/action-style-quality
  stylelint-reviewdog:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./web/themes/custom/mungo

      - name: Style Quality
        uses: reload/action-style-quality@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./web/themes/custom/mungo
          prettier_target: './assets_src/sass/**/*'
          stylelint_target: './assets_src/sass/**/*'
